############################################################
# Compound Heterozygous Parkinson's Disease Literature Review
#
# Victor Flores Ocampo et al.
#
# This script:
# 1. Updates literature search results
# 2. Harmonises reported variants
# 3. Annotates variants using ClinVar/HGMD/Genoox
# 4. Generates Annovar input files
# 5. Produces cleaned patient-level datasets
# 6. Generates manuscript summary statistics
#
# Some intermediate files are generated by the
# digenic-analysis workflow and are imported later.
############################################################


project_dir <- "."

raw_dir <- file.path(project_dir, "data", "raw")
query_dir <- file.path(project_dir, "data", "queries")
annot_dir <- file.path(project_dir, "data", "annotation")

output_dir <- file.path(project_dir, "results")
submission_dir <- file.path(project_dir, "results", "submission")

library(dplyr)
library(stringr)
library(stringi)
library(fuzzyjoin)
library(stringr)
library(readr)
library(tidyr)
library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)



project_dir <- "."

raw_dir <- file.path(project_dir, "data", "raw")
query_dir <- file.path(project_dir, "data", "queries")
annot_dir <- file.path(project_dir, "data", "annotation")
results_dir <- file.path(project_dir, "results")
submission_dir <- file.path(project_dir, "results", "submission")

# ==========================================================
# 1. Literature Search Update (2025 -> 2026)
# ==========================================================

#### updating to 2026

q_2026 <- read.csv(paste0(query_dir, "/PUBMED_CH_SEARCH_RESULTS_2026.csv"), header = TRUE)
q_2025 <- read.csv(paste0(query_dir, "/PUBMED_CH_SEARCH_RESULTS_2025.csv"), header = TRUE)

colnames(q_2025)

# standardise IDs
clean_ids <- function(df) {
  df %>%
    mutate(
      PMID = as.character(PMID),
      DOI  = str_to_lower(str_trim(DOI))
    )
}
q_2025 <- clean_ids(q_2025)
q_2026 <- clean_ids(q_2026)
q_2025 <- q_2025 %>%
  mutate(ID = ifelse(!is.na(PMID) & PMID != "", PMID, DOI))

q_2026 <- q_2026 %>%
  mutate(ID = ifelse(!is.na(PMID) & PMID != "", PMID, DOI))

overlap <- intersect(q_2025$ID, q_2026$ID)
length(overlap)
missing_in_2025 <- setdiff(q_2026$ID, q_2025$ID)

q_2026_missing <- q_2026 %>%
  filter(ID %in% missing_in_2025)


write.csv(q_2026_missing, paste0(query_dir,"/missing_udate.csv"), row.names = FALSE, quote = TRUE)



# ==========================================================
# 2. Load Compound Heterozygous Cases
# ==========================================================


ch_raw <- read.csv(paste0(raw_dir,"/CH_list_march17.csv"), sep = ",")


ch_raw$var_1_g <- paste0(ch_raw$Gene, "_", ch_raw$var_1_norm)
ch_raw$var_2_g <- paste0(ch_raw$Gene, "_", ch_raw$var_2_norm)

ch_raw <- ch_raw[, !grepl("^X", names(ch_raw))]

length(unique(ch_raw$DOI))

ch_raw <- ch_raw %>% 
  filter(Prune == "")


unique_variants <- unique(c(ch_raw$var_1_g, ch_raw$var_2_g))
table(ch_raw$Gene)

##### 101 papers 
length(unique(ch_raw$DOI))


# ==========================================================
# 3. Variant Annotation (ClinVar + HGMD + Genoox)
# ==========================================================


###################### Variant annotation USING CLINVAR
is_rearrangement <- grepl("_(Ex|ex).*(del|dup|inv|partial)", unique_variants)

unique_variants <- unique_variants[!is_rearrangement]

vars_refseq <- as.data.frame(unique_variants)

clinvar_dir <- paste0(annot_dir,"/clinvar_tables_extended") ### Directory containing one CLINVAR table per gene 

annotate_variant <- function(var) {
  
  gene <- sub("_.*", "", var)
  query <- sub(".*_[pc]\\.", "", var)
  
  file <- file.path(clinvar_dir, paste0(gene, ".txt"))
  
  if (!file.exists(file)) {
    return(data.frame(
      unique_variants = var,
      gene = gene,
      query = query,
      match_status = "gene_file_not_found",
      stringsAsFactors = FALSE
    ))
  }
  
  df <- read_tsv(
    file,
    col_types = cols(.default = col_character()),
    show_col_types = FALSE,
    name_repair = "unique"
  )
  
  hits <- df[grep(query, df$Name, fixed = TRUE), , drop = FALSE]
  
  if (nrow(hits) == 0) {
    return(data.frame(
      unique_variants = var,
      gene = gene,
      query = query,
      match_status = "no_match",
      stringsAsFactors = FALSE
    ))
  }
  
  hits$unique_variants <- var
  hits$gene <- gene
  hits$query <- query
  hits$match_status <- ifelse(nrow(hits) == 1, "matched", "multiple_matches")
  
  hits
}

results <- bind_rows(lapply(vars_refseq$unique_variants, annotate_variant))



hgmd_df <- read.csv(paste0(annot_dir,"/NBA_VARS.csv")) ### Supplementary table 5 from DOI: 10.1101/2023.11.06.23298176


vars_clean <- vars_refseq %>%
  mutate(
    gene = sub("_.*", "", unique_variants),
    aa = sub(".*_p\\.", "", unique_variants),
    
    aa_from = stringr::str_extract(aa, "^[A-Za-z]{3}"),
    aa_to   = stringr::str_extract(aa, "[A-Za-z]{3}$"),
    codon   = as.numeric(stringr::str_extract(aa, "[0-9]+")),
    
    is_trunc = stringr::str_detect(aa, "fs|Ter|\\*|X$"),
    
    aa_change = ifelse(
      is_trunc,
      paste0(aa_from, "-Term"),
      paste0(aa_from, "-", aa_to)
    )
  )

hgmd_clean <- hgmd_df %>%
  rename(
    gene = `Gene.symbol`,
    aa_change = `Amino.Acid.change`,
    codon = `Codon.number`,
    dbsnp = dbsnp,
    hgvs = HGVS
  ) %>%
  mutate(
    codon = as.numeric(codon)
  )

annotated <- vars_clean %>%
  left_join(hgmd_clean, by = c("gene", "aa_change", "codon"))

table(is.na(annotated$hgvs))

round2 <- merge(results, annotated, by = "unique_variants")

round2 <- round2 %>%
  mutate(
    captured = match_status=="matched" | !is.na(hgvs)
  )

table(round2$captured)

round2_noCNV <- round2[!grepl("Ex", round2$unique_variants), ]
table(round2_noCNV$captured)

not_annotated <- round2_noCNV %>%
  filter(match_status!="matched" & is.na(hgvs))


write.csv(not_annotated, 
          paste0(annot_dir,"/not_annotated_variants_RAW.csv"), 
          row.names = FALSE)



############## Manual annotated variants using Genoox service Franklin: https://franklin.genoox.com/
##############
############## manual annotation done on "not_annotated" file or "/not_annotated_variants_RAW.csv"
##############

genoox_raw <- read.csv(paste0(annot_dir,"/not_annotated_variants.csv"))

round3 <- merge(round2, genoox_raw, by = "unique_variants", all = TRUE)

toannot <- round3
colnames(toannot)




# ==========================================================
# 4. CPRA Harmonisation
# ==========================================================

# Parsing columns from different sources to get CPRA 


# ----------------------------
# 1) helper: complement bases
# ----------------------------
comp_base <- function(x) {
  x <- toupper(x)
  chartr("ACGT", "TGCA", x)
}

# ----------------------------
# 2) ClinVar SPDI -> CPRA
# example:
# NC_000006.12:162443313:A:T  ->  6:162443314:A:T
# IMPORTANT: +1 to position
# ----------------------------
spdi_to_cpra <- function(spdi) {
  if (is.na(spdi) || spdi == "") return(NA_character_)
  
  parts <- str_split(spdi, ":", simplify = TRUE)
  if (ncol(parts) < 4) return(NA_character_)
  
  seqid <- parts[1]
  pos0  <- suppressWarnings(as.numeric(parts[2]))
  ref   <- parts[3]
  alt   <- parts[4]
  
  chr <- str_match(seqid, "^NC_0*([0-9XYM]+)\\.[0-9]+$")[,2]
  if (is.na(chr) || is.na(pos0)) return(NA_character_)
  
  pos1 <- pos0 + 1
  
  paste(chr, pos1, ref, alt, sep = ":")
}

# ----------------------------
# 3) NBA coords + Base.change -> CPRA
# examples:
# Genomic.coordinates..GRCh38. = "chr6:161386823 (-)"
# Base.change = "C-T"
# if strand == -, complement both alleles
# ----------------------------
nba_to_cpra <- function(coord, base_change) {
  if (is.na(coord) || coord == "" || is.na(base_change) || base_change == "") {
    return(NA_character_)
  }
  
  chr <- str_match(coord, "^chr([0-9XYM]+):")[,2]
  pos <- str_match(coord, "^chr[0-9XYM]+:([0-9]+)")[,2]
  strand <- str_match(coord, "\\(([+-])\\)")[,2]
  
  bc <- str_split(base_change, "-", simplify = TRUE)
  if (ncol(bc) < 2) return(NA_character_)
  
  ref <- toupper(trimws(bc[1]))
  alt <- toupper(trimws(bc[2]))
  
  if (is.na(chr) || is.na(pos) || is.na(strand)) return(NA_character_)
  
  if (strand == "-") {
    ref <- comp_base(ref)
    alt <- comp_base(alt)
  }
  
  paste(chr, pos, ref, alt, sep = ":")
}

# ----------------------------
# 4) Genoox string -> CPRA
# example:
# chr1-7969392 GAAT>G  ->  1:7969392:GAAT:G
# ----------------------------
genoox_to_cpra <- function(x) {
  if (is.na(x) || x == "") return(NA_character_)
  
  m <- str_match(x, "^chr([0-9XYM]+)-([0-9]+)\\s+([^>]+)>(.+)$")
  chr <- m[,2]
  pos <- m[,3]
  ref <- m[,4]
  alt <- m[,5]
  
  if (is.na(chr) || is.na(pos) || is.na(ref) || is.na(alt)) return(NA_character_)
  
  paste(chr, pos, ref, alt, sep = ":")
}

# ----------------------------
# 5) build final comparison df
# ----------------------------
cpra_df <- toannot %>%
  transmute(
    unique_variants,
    CPRA_CLINVAR = sapply(.data$`Canonical SPDI`, spdi_to_cpra),
    CPRA_NBA     = mapply(
      nba_to_cpra,
      .data$`Genomic.coordinates..GRCh38.`,
      .data$`Base.change`,
      USE.NAMES = FALSE
    ),
    CPRA_GENOOX  = sapply(.data$genoox, genoox_to_cpra)
  ) %>%
  distinct(unique_variants, .keep_all = TRUE)



cpra_final <- cpra_df %>%
  mutate(
    CPRA = coalesce(CPRA_GENOOX, CPRA_CLINVAR, CPRA_NBA)
  ) %>%
  select(unique_variants, CPRA, CPRA_GENOOX, CPRA_CLINVAR, CPRA_NBA)



missing <- cpra_final %>% filter(is.na(CPRA))
missing


# ==========================================================
# 5. Annovar Preparation
# ==========================================================

annovar_input <- cpra_final %>%
  filter(!is.na(CPRA)) %>%
  separate(CPRA, into = c("chr", "pos", "ref", "alt"), sep = ":", remove = FALSE) %>%
  mutate(
    pos = as.numeric(pos),
    start = pos,
    end = pos + nchar(ref) - 1
  ) %>%
  select(chr, start, end, ref, alt, unique_variants, CPRA)



vcf_df <- cpra_final %>%
  filter(!is.na(CPRA)) %>%
  separate(CPRA, into = c("CHROM", "POS", "REF", "ALT"), sep = ":", remove = FALSE) %>%
  mutate(
    CHROM = paste0("chr", CHROM),
    POS = as.integer(POS),
    ID = unique_variants,
    REF = ifelse(is.na(REF) | REF == "", "-", REF),
    ALT = ifelse(is.na(ALT) | ALT == "", "-", ALT),
    QUAL = ".",
    FILTER = ".",
    INFO = "."
  ) %>%
  select(CHROM, POS, ID, REF, ALT, QUAL, FILTER, INFO)

contigs <- sort(unique(vcf_df$CHROM))

vcf_path <- paste0(annot_dir,"/variants_raw.vcf")

con <- file(vcf_path, "w")
writeLines("##fileformat=VCFv4.2", con)
writeLines("##source=cpra_from_manual_merge", con)
writeLines(paste0("##contig=<ID=", contigs, ">"), con)
writeLines("#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO", con)
close(con)

write.table(
  vcf_df,
  file = vcf_path,
  sep = "\t",
  row.names = FALSE,
  col.names = FALSE,
  quote = FALSE,
  append = TRUE
)

######### Normalisation step:

#manually corrected indels 

#chr6  162262560  PRKN_p.Pro113fs  TCAGTGTGCAGAATGACAGCCAGCCCCACAGAGTCTCCTGG  T
#chr6    161548965    PRKN_p.Val324fs    GA    G


############## Next section of code is excecutable in Bash



#bcftools norm -f hg38.fa -Oz -o variants_norm.vcf.gz variants_raw.vcf

#perl utils/annovar/convert2annovar.pl \
#-format vcf4 \
#-allsample \
#-withfreq \
#/variants_norm.vcf.gz \
#> /variants_norm.avinput

#perl /utils/annovar/table_annovar.pl \
#/variants_norm.avinput \
#/utils/annovar/humandb/ \
#-buildver hg38 \
#-out /variants_annotated \
#-remove \
#-protocol refGene,clinvar_20250721,dbnsfp47a \
#-operation g,f,f \
#-nastring . \
#-polish \
#-xreffile /utils/annovar/example/gene_xref.txt


#bcftools view variants_norm.vcf.gz | grep -v "##" > variants_noralised_vcf_IDs.tsv




# ==========================================================
# 6. Variant Filtering and Cleaning
# ==========================================================

norm_Ids <- read.csv("variants_noralised_vcf_IDs.tsv", sep = "\t", header = TRUE)

norm_Ids$unique_variants <- norm_Ids$ID
norm_Ids$CPRA <- paste0(norm_Ids$X.CHROM,":", norm_Ids$POS, ":", norm_Ids$REF, ":", norm_Ids$ALT)


###### Adding Annovar output
annovar_raw <- read.csv("variants_annotated.hg38_multianno.txt", sep = "\t", header = TRUE)

annovar <- bind_cols(annovar_raw,norm_Ids)
colnames(annovar)

cols_to_keep <- c(
  "Chr", "Start", "End",
  "Ref", "Alt",
  "Func.refGene", "Gene.refGene", "GeneDetail.refGene",
  "ExonicFunc.refGene", "AAChange.refGene",
  "unique_variants", "CPRA","CLNALLELEID",	"CLNDN",	"CLNDISDB",	"CLNREVSTAT",	"CLNSIG"
)

annovar <- annovar[,cols_to_keep]

final_annot <- merge(annovar,norm_Ids, by = "unique_variants" )

write.csv(final_annot, 
          "FINAL_ANNOTATED_VARIANTS.csv", 
          row.names = FALSE)

colnames(final_annot)



########################################################## Harmonizing variants across CH Px table

sum(final_annot$CPRA.x != final_annot$CPRA.y, na.rm = TRUE)

final_annot[final_annot$CPRA.x != final_annot$CPRA.y & 
              !is.na(final_annot$CPRA.x) & !is.na(final_annot$CPRA.y), 
            c("unique_variants", "CPRA.x", "CPRA.y")]
final_annot$CPRA <- final_annot$CPRA.x

####### checking which variants have more that one refseq ID

dup_vars <- final_annot[duplicated(final_annot$CPRA) | duplicated(final_annot$CPRA, fromLast = TRUE), 
                        c("unique_variants", "CPRA", "Gene.refGene", "AAChange.refGene")]

dup_vars <- dup_vars[order(dup_vars$CPRA), ]
dup_vars
cpra_counts <- as.data.frame(table(final_annot$CPRA), stringsAsFactors = FALSE)
cpra_counts <- cpra_counts[cpra_counts$Freq > 1, ]
cpra_counts

## Choosing a canonical refseq ID


canonical_map <- final_annot %>%
  mutate(
    CPRA = ifelse(!is.na(CPRA.x), CPRA.x, CPRA.y),
    is_protein = grepl("_p\\.", unique_variants)
  ) %>%
  group_by(CPRA) %>%
  arrange(desc(is_protein), unique_variants, .by_group = TRUE) %>%
  summarise(canonical_variant = first(unique_variants), .groups = "drop")

############################################# Mapping variants that changed name
variant_update_map <- final_annot %>%
  mutate(CPRA = ifelse(!is.na(CPRA.x), CPRA.x, CPRA.y)) %>%
  select(unique_variants, CPRA) %>%
  left_join(canonical_map, by = "CPRA") %>%
  mutate(deprecated = unique_variants != canonical_variant) %>%
  arrange(CPRA, unique_variants)
variant_update_map %>%
  filter(deprecated)

#################### Update patient table
lookup <- setNames(variant_update_map$canonical_variant, variant_update_map$unique_variants)

ch_raw$var_1_g <- ifelse(ch_raw$var_1_g %in% names(lookup), lookup[ch_raw$var_1_g], ch_raw$var_1_g)
ch_raw$var_2_g <- ifelse(ch_raw$var_2_g %in% names(lookup), lookup[ch_raw$var_2_g], ch_raw$var_2_g)

table(ch_raw$Gene)


########################## sanity check
## FILTERED OUT BENING VARIANTS
benign_vars <- final_annot %>%
  filter(str_detect(CLNSIG, regex("benign", ignore_case = TRUE))) %>%
  pull(unique_variants) %>%
  unique()

ch_filtered <- ch_raw %>%
  filter(
    !var_1_g %in% benign_vars,
    !var_2_g %in% benign_vars
  )


##Checking homozygotes
ch_filtered <- ch_filtered %>%
  filter(var_1_g != var_2_g)  # remove homozygotes

## Excluding cases without enough genetic data ( no annotation available)
fix_sv <- function(x) {
  x %>%
    str_replace_all("–", "-") %>% 
    str_replace_all("Ex(\\d+)_([0-9P]+)", "Ex\\1-\\2")
}

is_rearrangement <- function(x) {
  grepl("_(Ex|ex).*(del|dup|inv|partial)", x)
}

ch_filtered <- ch_filtered %>%
  mutate(
    var_1_g = fix_sv(var_1_g),
    var_2_g = fix_sv(var_2_g)
  )

annot_vars <- unique(final_annot$unique_variants)

ch_filtered <- ch_filtered %>%
  filter(
    (var_1_g %in% annot_vars | is_rearrangement(var_1_g)),
    (var_2_g %in% annot_vars | is_rearrangement(var_2_g))
  )


vars_all <- unique(c(as.character(ch_filtered$var_1_g), as.character(ch_filtered$var_2_g)))
vars_all <- vars_all[!is.na(vars_all)]

is_rearrangement <- grepl("_(Ex|ex).*(del|dup|inv|partial)", vars_all)

vars_rearr <- sort(vars_all[is_rearrangement])
vars_seq   <- sort(vars_all[!is_rearrangement])



vars_all_clean <-  tibble(full = vars_all) %>%
  separate(full, into = c("gene", "variant"), sep = "_", extra = "merge")

SVs_clean <-  tibble(full = vars_rearr) %>%
  separate(full, into = c("gene", "variant"), sep = "_", extra = "merge")

SNVs_clean <-  tibble(full = vars_seq) %>%
  separate(full, into = c("gene", "variant"), sep = "_", extra = "merge")



SNVs_clean$unique_variants <- paste0(SNVs_clean$gene,"_", SNVs_clean$variant)
SNVs_clean <- merge(SNVs_clean, final_annot, by = "unique_variants")
SVs_clean$unique_variants <- paste0(SVs_clean$gene,"_", SVs_clean$variant)



missing_seq <- setdiff(as.character(vars_seq), as.character(final_annot$unique_variants))
missing_seq


write.csv(
  ch_filtered,
  "/CH_CLEANLIST.csv",
  row.names = FALSE,
  fileEncoding = "UTF-8"
)


write.csv(SNVs_clean, 
          "/SNV_CLEANLIST.csv", 
          row.names = FALSE)
write.csv(SVs_clean, 
          "/SVs_CLEANLIST.csv", 
          row.names = FALSE)

length(ch_filtered$IID)


length(unique(ch_filtered$DOI))
length(ch_filtered$IID)

# ==========================================================
# 8. Manuscript Statistics
# ==========================================================


################# PAPERRRR
length(vars_all)
####Number of variants per gene
table(vars_all_clean$gene)

##number of cases per gene
table(ch_filtered$Gene)

## exonic function classification per SNV and small indel (no SVs)
length(SNVs_clean$unique_variants)
table(SNVs_clean$ExonicFunc.refGene)

### Number of rearrangements
length(SVs_clean$variant)


table(str_extract(unique(SVs_clean$variant), "del|dup|inv")) ##types or rearrs




################################### By Gene numbers on literature works
PRKN_raw <- ch_filtered %>%
  filter(Gene == "PRKN")

length(unique(PRKN_raw$PAPER_N))

paper_prkn <- merge(PRKN_raw, q_2026, by = "DOI")
paper_prkn <- paper_prkn[!duplicated(paper_prkn$DOI), ]
paper_prkn <- paper_prkn[,c("DOI", "First.Author", "Publication.Year", "Journal.Book")]


paper_prkn_clean <- paper_prkn %>%
  mutate(
    surname = extract_surname_ch(First.Author),
    year = as.integer(Publication.Year)
  )
mds_refs_clean <- mds_refs %>%
  mutate(
    surname = extract_surname_mds(Study),
    year = extract_year_mds(Study)
  )

matches_exact <- paper_prkn_clean %>%
  left_join(
    mds_refs_clean,
    by = c("surname", "year"),
    suffix = c("_ch", "_mds")
  )
# duplicated keys in ch_refs
paper_prkn_clean %>%
  count(surname, year, sort = TRUE) %>%
  filter(n > 1)
# duplicated keys in mds_refs
mds_refs_clean %>%
  count(surname, year, sort = TRUE) %>%
  filter(n > 1)
# show duplicated rows in ch_refs
paper_prkn_clean %>%
  add_count(surname, year) %>%
  filter(n > 1) %>%
  arrange(surname, year) %>%
  select(First.Author, Publication.Year, Journal.Book, surname, year)
# show duplicated rows in mds_refs
mds_refs_clean %>%
  add_count(surname, year) %>%
  filter(n > 1) %>%
  arrange(surname, year) %>%
  select(Study, surname, year)
matches_all <- ch_refs_clean %>%
  inner_join(mds_refs_clean, by = c("surname", "year"), suffix = c("_ch", "_mds"))
# unique matches only
unique_matches <- matches_all %>%
  add_count(First.Author, Publication.Year, name = "n_matches") %>%
  filter(n_matches == 1)
# ambiguous matches needing review
ambiguous_matches <- matches_all %>%
  add_count(First.Author, Publication.Year, name = "n_matches") %>%
  filter(n_matches > 1) %>%
  arrange(First.Author, Publication.Year)


##########################################################################################################

PARK7_raw <- ch_filtered %>%
  filter(Gene == "DJ-1")

length(unique(PARK7_raw$PAPER_N))

paper_park7 <- merge(PARK7_raw, q_2026, by = "DOI")
paper_park7 <- paper_park7[!duplicated(paper_park7$DOI), ]
paper_park7 <- paper_park7[,c("DOI", "First.Author", "Publication.Year", "Journal.Book")]


paper_park7_clean <- paper_park7 %>%
  mutate(
    surname = extract_surname_ch(First.Author),
    year = as.integer(Publication.Year)
  )
mds_refs_clean <- mds_refs %>%
  mutate(
    surname = extract_surname_mds(Study),
    year = extract_year_mds(Study)
  )

matches_exact <- paper_park7_clean %>%
  left_join(
    mds_refs_clean,
    by = c("surname", "year"),
    suffix = c("_ch", "_mds")
  )
# duplicated keys in ch_refs
paper_park7_clean %>%
  count(surname, year, sort = TRUE) %>%
  filter(n > 1)
# duplicated keys in mds_refs
mds_refs_clean %>%
  count(surname, year, sort = TRUE) %>%
  filter(n > 1)
# show duplicated rows in ch_refs
paper_park7_clean %>%
  add_count(surname, year) %>%
  filter(n > 1) %>%
  arrange(surname, year) %>%
  select(First.Author, Publication.Year, Journal.Book, surname, year)
# show duplicated rows in mds_refs
mds_refs_clean %>%
  add_count(surname, year) %>%
  filter(n > 1) %>%
  arrange(surname, year) %>%
  select(Study, surname, year)
matches_all <- ch_refs_clean %>%
  inner_join(mds_refs_clean, by = c("surname", "year"), suffix = c("_ch", "_mds"))
# unique matches only
unique_matches <- matches_all %>%
  add_count(First.Author, Publication.Year, name = "n_matches") %>%
  filter(n_matches == 1)
# ambiguous matches needing review
ambiguous_matches <- matches_all %>%
  add_count(First.Author, Publication.Year, name = "n_matches") %>%
  filter(n_matches > 1) %>%
  arrange(First.Author, Publication.Year)



#################################################################################################


PINK1_raw <- ch_filtered %>%
  filter(Gene == "PINK1")

length(unique(PINK1_raw$PAPER_N))

paper_pink1 <- merge(PINK1_raw, q_2026, by = "DOI")
paper_pink1 <- paper_pink1[!duplicated(paper_pink1$DOI), ]
paper_pink1 <- paper_pink1[,c("DOI", "First.Author", "Publication.Year", "Journal.Book")]


paper_pink1_clean <- paper_pink1 %>%
  mutate(
    surname = extract_surname_ch(First.Author),
    year = as.integer(Publication.Year)
  )
mds_refs_clean <- mds_refs %>%
  mutate(
    surname = extract_surname_mds(Study),
    year = extract_year_mds(Study)
  )

matches_exact <- paper_pink1_clean %>%
  left_join(
    mds_refs_clean,
    by = c("surname", "year"),
    suffix = c("_ch", "_mds")
  )
# duplicated keys in ch_refs
paper_pink1_clean %>%
  count(surname, year, sort = TRUE) %>%
  filter(n > 1)
# duplicated keys in mds_refs
mds_refs_clean %>%
  count(surname, year, sort = TRUE) %>%
  filter(n > 1)
# show duplicated rows in ch_refs
paper_pink1_clean %>%
  add_count(surname, year) %>%
  filter(n > 1) %>%
  arrange(surname, year) %>%
  select(First.Author, Publication.Year, Journal.Book, surname, year)
# show duplicated rows in mds_refs
mds_refs_clean %>%
  add_count(surname, year) %>%
  filter(n > 1) %>%
  arrange(surname, year) %>%
  select(Study, surname, year)

matches_all <- paper_pink1_clean %>%
  inner_join(mds_refs_clean, by = c("surname", "year"), suffix = c("_ch", "_mds"))
# unique matches only
unique_matches <- matches_all %>%
  add_count(First.Author, Publication.Year, name = "n_matches") %>%
  filter(n_matches == 1)
# ambiguous matches needing review
ambiguous_matches <- matches_all %>%
  add_count(First.Author, Publication.Year, name = "n_matches") %>%
  filter(n_matches > 1) %>%
  arrange(First.Author, Publication.Year)


#######

noEOPD_raw <- ch_filtered %>%
  filter(Gene != "PINK1" | Gene != "DJ-1" | Gene != "PRKN")

length(unique(noEOPD_raw$DOI))

## 66 PRKN, 13 PINK1, 1 DJ1 -- > 80 / 98
80/98
18/98

ch_aao <- ch_filtered %>%
  filter(
    !is.na(Age.at.Onset),
    Age.at.Onset != "",
    !tolower(Age.at.Onset) %in% c("na", "no info", "not reported", "?", "NA", "<30")
  )

264/307
summary(as.integer(ch_aao$Age.at.Onset))
sd(as.numeric(ch_aao$Age.at.Onset), na.rm = TRUE)

################################################# Stuff for table1

ch_aoo_sex <- ch_filtered %>%
  filter(
    !is.na(Age.at.Onset),
    Age.at.Onset != "",
    !tolower(Age.at.Onset) %in% c("na", "no info", "not reported", "?", "NA", "<30"),
    !is.na(Sex),
    Sex != "",
    !tolower(Sex) %in% c("na", "no info", "not reported", "?", "NA")
  )

males_age <- ch_aoo_sex %>%
  filter(Sex == "M")
summary(as.integer(males_age$Age.at.Onset))
sd(as.numeric(males_age$Age.at.Onset), na.rm = TRUE)

females_age <- ch_aoo_sex %>%
  filter(Sex == "F")
summary(as.integer(females_age$Age.at.Onset))
sd(as.numeric(females_age$Age.at.Onset), na.rm = TRUE)

ch_aoo_pop <- ch_filtered %>%
  filter(
    !is.na(Age.at.Onset),
    Age.at.Onset != "",
    !tolower(Age.at.Onset) %in% c("na", "no info", "not reported", "?", "NA", "<30"),
    !is.na(Population),
    Population != "",
    !tolower(Population) %in% c("na", "no info", "not reported", "?", "NA")
  )
ch_aoo_pop <- ch_aoo_pop %>%
  mutate(
    Population_clean = str_to_lower(Population),
    Population_continent = case_when(
      
      # EUROPE
      str_detect(Population_clean, "europe|caucasian|french|german|irish|italian|italy|polish|serbian|swiss|uk|ukrainian|czech|netherlands|polish|finnland|france|belgian|spain|norway") ~ "EUR",
      
      #Middle East
      str_detect(Population_clean, "cyprus|turkish|yemen") ~ "MDE",
      
      # EAST ASIA
      str_detect(Population_clean, "china|chinese|japan|japanese|korea|korean|taiwan|vietnam|filipino") ~ "EAS",
      
      # AFRICA
      str_detect(Population_clean, "african|tunisia") ~ "AFR",
      
      # LATIN AMERICA / ADMIXED AMERICAN
      str_detect(Population_clean, "mexico|mexican|brazil|peru") ~ "AMR",
      
      # NORTH AMERICA (ambiguous, likely EUR )
      str_detect(Population_clean, "north american") ~ "EUR",
      
      TRUE ~ "Other"
    )
  )

age_AFR <- ch_aoo_pop %>%
  filter(Population_continent == "AFR")
summary(as.integer(age_AFR$Age.at.Onset))
sd(as.numeric(age_AFR$Age.at.Onset), na.rm = TRUE)

age_AMR <- ch_aoo_pop %>%
  filter(Population_continent == "AMR")
summary(as.integer(age_AMR$Age.at.Onset))
sd(as.numeric(age_AMR$Age.at.Onset), na.rm = TRUE)

age_EAS <- ch_aoo_pop %>%
  filter(Population_continent == "EAS")
summary(as.integer(age_EAS$Age.at.Onset))
sd(as.numeric(age_EAS$Age.at.Onset), na.rm = TRUE)

age_EUR <- ch_aoo_pop %>%
  filter(Population_continent == "EUR")
summary(as.integer(age_EUR$Age.at.Onset))
sd(as.numeric(age_EUR$Age.at.Onset), na.rm = TRUE)

age_MDE <- ch_aoo_pop %>%
  filter(Population_continent == "MDE")
summary(as.integer(age_MDE$Age.at.Onset))
sd(as.numeric(age_MDE$Age.at.Onset), na.rm = TRUE)


ch_sex <- ch_filtered %>%
  filter(
    !is.na(Sex),
    Sex != "",
    !tolower(Sex) %in% c("na", "no info", "not reported", "?", "NA")
  )
224/307
table(ch_sex$Sex)

ch_ancestry <- ch_filtered %>%
  filter(
    !is.na(Population),
    Population != "",
    !tolower(Population) %in% c("na", "no info", "not reported", "?", "NA")
  )
306/307

ch_ancestry <- ch_ancestry %>%
  mutate(
    Population_clean = str_to_lower(Population),
    Population_continent = case_when(
      
      # EUROPE
      str_detect(Population_clean, "europe|caucasian|french|german|irish|italian|italy|polish|serbian|swiss|uk|ukrainian|czech|netherlands|polish|finnland|france|belgian|spain|norway") ~ "EUR",
      
      #Middle East
      str_detect(Population_clean, "cyprus|turkish|yemen") ~ "MDE",
      
      # EAST ASIA
      str_detect(Population_clean, "china|chinese|japan|japanese|korea|korean|taiwan|vietnam|filipino") ~ "EAS",
      
      # AFRICA
      str_detect(Population_clean, "african|tunisia") ~ "AFR",
      
      # LATIN AMERICA / ADMIXED AMERICAN
      str_detect(Population_clean, "mexico|mexican|brazil|peru") ~ "AMR",
      
      # NORTH AMERICA (ambiguous, likely EUR )
      str_detect(Population_clean, "north american") ~ "EUR",
      
      TRUE ~ "Other"
    )
  )

table(ch_ancestry$Population_continent)

#EUR
176/307
#AFR
5/307
#EAS
87/307
#MDE
8/307
#AMR
30/307

############################################################################################################################################
########################################################################## PRKN ######################################################################
############################################################################################################################################
############################################################################################################################################
prkn_vars_raw <- SNVs_clean %>%
  filter(Gene.refGene == "PRKN")
PRKN_raw <- ch_filtered %>%
  filter(Gene == "PRKN")

length(unique(PRKN_raw$PAPER_N))

length(unique(c(PRKN_raw$var_1_g,PRKN_raw$var_2_g)))


##96 unique variants (all)
library(purrr)

######## Checking rearrangements

rear_prkn <- SVs_clean %>%
  filter(gene == "PRKN")

length(rear_prkn$variant)

####### Checking exons mentioned:

prkn_exon_summary <- rear_prkn %>%
  mutate(
    prkn_exon_raw = str_replace_all(unique_variants, "–|_", "-"),
    prkn_exon_raw = str_extract(prkn_exon_raw, "Ex[0-9P-]+"),
    prkn_exon_raw = str_remove(prkn_exon_raw, "^Ex"),
    prkn_exon = map(prkn_exon_raw, \(x) {
      if (is.na(x) || str_detect(x, "P")) return(NA_integer_)
      if (str_detect(x, "-")) {
        bounds <- as.numeric(str_split(x, "-", simplify = TRUE))
        seq(bounds[1], bounds[2])
      } else {
        as.numeric(x)
      }
    })
  ) %>%
  unnest(prkn_exon) %>%
  filter(!is.na(prkn_exon))

sort(unique(prkn_exon_summary$prkn_exon))   # unique exons mentioned

length(unique(prkn_exon_summary$unique_variants)) ##  different exon rearrangements

table(prkn_exon_summary$prkn_exon)          # counts per exon (including multi-exon events)

table(str_extract(unique(prkn_exon_summary$unique_variants), "del|dup|inv")) ##types or rearrs in PRKN

###### check span of exon rearrangements: 
sv_prks_span <- tibble(x = unique(prkn_exon_summary$unique_variants)) %>%
  mutate(
    start = as.integer(str_extract(x, "(?<=Ex)\\d+")),
    end   = as.integer(str_extract(x, "(?<=-)\\d+")),
    end   = ifelse(is.na(end), start, end),
    n_exons = end - start + 1
  )

sv_prks_span

### deletions
sv_prks_span %>%
  mutate(type = str_extract(x, "del|dup|inv")) %>%
  filter(type == "del", n_exons == 1) %>%
  count(start, sort = TRUE)%>%
  arrange(start)

### duplications
sv_prks_span %>%
  mutate(type = str_extract(x, "del|dup|inv")) %>%
  filter(type == "dup", n_exons == 1) %>%
  count(start, sort = TRUE)%>%
  arrange(start)

### invertions
sv_prks_span %>%
  mutate(type = str_extract(x, "del|dup|inv")) %>%
  filter(type == "del", n_exons == 1) %>%
  count(start, sort = TRUE)%>%
  arrange(start)


sv_prks_span%>%
  mutate(type = str_extract(x, "del|dup|inv")) %>%
  group_by(type) %>%
  summarise(max_exons = max(n_exons, na.rm = TRUE))



####################################################### Checking SNVs and small indels
length(prkn_vars_raw$ExonicFunc.refGene)
## 52 variants SNV / small indels
table(prkn_vars_raw$ExonicFunc.refGene)
#"." are splice variants

###################################################### counts per variant

length(prkn_vars_raw$unique_variants)
## 44 unique SNVs 

## 44 Short vars + 51 exon rearrangements

var_freq_prkn <- PRKN_raw %>%
  select(var_1_g, var_2_g) %>%
  pivot_longer(cols = everything(), values_to = "variant") %>%
  filter(!is.na(variant)) %>%
  count(variant, sort = TRUE)

var_freq_prkn               ### Most common variants (individually)



pairs_prkn <- PRKN_raw %>%
  filter(!is.na(var_1_g), !is.na(var_2_g)) %>%
  mutate(
    var_a = pmin(var_1_g, var_2_g),
    var_b = pmax(var_1_g, var_2_g)
  ) %>%
  count(var_a, var_b, sort = TRUE)

##################################################### Checking top partners for any given variant
pairs_prkn %>%
  filter(var_a == "PRKN_Ex4del")

target_pair <- c("PRKN_Ex7del", "PRKN_p.Val324fs")

target_literature <- PRKN_raw %>%
  rowwise() %>%
  filter(setequal(c(var_1_g, var_2_g), target_pair)) %>%
  ungroup()

unique(target_literature$PAPER_N)

###########percentage of rearangements

pairs_prkn %>%
  mutate(
    rearr_a = str_detect(var_a, "Ex"),
    rearr_b = str_detect(var_b, "Ex")
  ) %>%
  mutate(
    category = case_when(
      rearr_a & rearr_b ~ "rearr + rearr",
      rearr_a | rearr_b ~ "rearr + SNV",
      TRUE ~ "SNV + SNV"
    )
  ) %>%
  group_by(category) %>%
  summarise(n = sum(n), .groups = "drop")

# SNV + SNV        36 --> 36/241 (14.93%)
# rearr + SNV     115 --> 115/241 (47.71%)
# rearr + rearr    90 --> 90/241 (37.34)



write.csv(pairs_prkn, 
          "variant_pair_ranking.csv", 
          row.names = FALSE)


length(unique(PRKN_raw$PAPER_N))
## 243 cases accross 64 papers
## 2 cases dropped after benign variants filtered out


############################################################################## Population stratification

table(PRKN_raw$Population)

PRKN_raw <- PRKN_raw %>%
  mutate(
    Population_clean = str_to_lower(Population),
    Population_continent = case_when(
      
      # EUROPE
      str_detect(Population_clean, "europe|caucasian|french|german|irish|italian|italy|polish|serbian|swiss|uk|ukrainian|czech|netherlands|polish|finnland|france|belgian|spain|norway") ~ "EUR",
      
      #Middle East
      str_detect(Population_clean, "cyprus|turkish|yemen") ~ "MDE",
      
      # EAST ASIA
      str_detect(Population_clean, "china|chinese|japan|japanese|korea|korean|taiwan|vietnam|filipino") ~ "EAS",
      
      # AFRICA
      str_detect(Population_clean, "african|tunisia") ~ "AFR",
      
      # LATIN AMERICA / ADMIXED AMERICAN
      str_detect(Population_clean, "mexico|mexican|brazil|peru") ~ "AMR",
      
      # NORTH AMERICA (ambiguous, likely EUR )
      str_detect(Population_clean, "north american") ~ "EUR",
      
      TRUE ~ "Other"
    )
  )



table(PRKN_raw$Population_continent)

pairs_by_continent <- PRKN_raw %>%
  filter(!is.na(var_1_g), !is.na(var_2_g), !is.na(Population_continent)) %>%
  mutate(
    var_a = pmin(var_1_g, var_2_g),
    var_b = pmax(var_1_g, var_2_g)
  ) %>%
  count(Population_continent, var_a, var_b, sort = TRUE)

top_pairs_by_continent <- pairs_by_continent %>%
  group_by(Population_continent) %>%
  slice_max(n, n = 5, with_ties = FALSE) %>%
  ungroup()

top_pairs_by_continent


###### check exclusivity

pair_exclusivity <- pairs_by_continent %>%
  group_by(var_a, var_b) %>%
  mutate(n_continents = n_distinct(Population_continent)) %>%
  ungroup()
exclusive_pairs <- pair_exclusivity %>%
  filter(n_continents == 1)

exclusive_pairs %>%
  arrange(Population_continent, desc(n))

exclusive_summary <- pairs_by_continent %>%
  group_by(var_a, var_b) %>%
  mutate(n_continents = n_distinct(Population_continent)) %>%
  ungroup() %>%
  mutate(is_exclusive = n_continents == 1) %>%
  group_by(Population_continent) %>%
  summarise(
    total_pairs = n(),                         # number of distinct pairs in that continent
    exclusive_pairs = sum(is_exclusive),       # how many are exclusive
    prop_exclusive = exclusive_pairs / total_pairs
  )

exclusive_summary

############################################################################################################################################
########################################################################## PINK1 ######################################################################
############################################################################################################################################
############################################################################################################################################
pink1_vars_raw <- SNVs_clean %>%
  filter(Gene.refGene == "PINK1")

PINK1_raw <- ch_filtered %>%
  filter(Gene == "PINK1")

length(unique(PINK1_raw$PAPER_N))

length(unique(c(PINK1_raw$var_1_g,PINK1_raw$var_2_g)))

length(PINK1_raw$IID)
##96 unique variants (all)
library(purrr)

######## Checking rearrangements

rear_pink1 <- SVs_clean %>%
  filter(gene == "PINK1")

####### Checking exons mentioned:

pink1_exon_summary <- rear_pink1 %>%
  mutate(
    pink1_exon_raw = str_replace_all(unique_variants, "–|_", "-"),
    pink1_exon_raw = str_extract(pink1_exon_raw, "Ex[0-9P-]+"),
    pink1_exon_raw = str_remove(pink1_exon_raw, "^Ex"),
    pink1_exon = map(pink1_exon_raw, \(x) {
      if (is.na(x) || str_detect(x, "P")) return(NA_integer_)
      if (str_detect(x, "-")) {
        bounds <- as.numeric(str_split(x, "-", simplify = TRUE))
        seq(bounds[1], bounds[2])
      } else {
        as.numeric(x)
      }
    })
  ) %>%
  unnest(pink1_exon) %>%
  filter(!is.na(pink1_exon))

sort(unique(pink1_exon_summary$pink1_exon))   # unique exons mentioned

length(unique(pink1_exon_summary$unique_variants)) ## 59 different exon rearrangements

table(pink1_exon_summary$pink1_exon)          # counts per exon (including multi-exon events)

table(str_extract(unique(pink1_exon_summary$unique_variants), "del|dup|inv")) ##types or rearrs in pink1

###### check span of exon rearrangements: 
sv_prks_span <- tibble(x = unique(pink1_exon_summary$unique_variants)) %>%
  mutate(
    start = as.integer(str_extract(x, "(?<=Ex)\\d+")),
    end   = as.integer(str_extract(x, "(?<=-)\\d+")),
    end   = ifelse(is.na(end), start, end),
    n_exons = end - start + 1
  )

sv_prks_span

### deletions
sv_prks_span %>%
  mutate(type = str_extract(x, "del|dup|inv")) %>%
  filter(type == "del", n_exons == 1) %>%
  count(start, sort = TRUE)%>%
  arrange(start)

### duplications
sv_prks_span %>%
  mutate(type = str_extract(x, "del|dup|inv")) %>%
  filter(type == "dup", n_exons == 1) %>%
  count(start, sort = TRUE)%>%
  arrange(start)

### invertions
sv_prks_span %>%
  mutate(type = str_extract(x, "del|dup|inv")) %>%
  filter(type == "del", n_exons == 1) %>%
  count(start, sort = TRUE)%>%
  arrange(start)


sv_prks_span%>%
  mutate(type = str_extract(x, "del|dup|inv")) %>%
  group_by(type) %>%
  summarise(max_exons = max(n_exons, na.rm = TRUE))



####################################################### Checking SNVs and small indels
length(pink1_vars_raw$ExonicFunc.refGene)
## 52 variants SNV / small indels
table(pink1_vars_raw$ExonicFunc.refGene)
#"." are splice variants

###################################################### counts per variant

length(pink1_vars_raw$unique_variants)
## 44 unique SNVs 

## 44 Short vars + 51 exon rearrangements

var_freq_pink1 <- PINK1_raw %>%
  select(var_1_g, var_2_g) %>%
  pivot_longer(cols = everything(), values_to = "variant") %>%
  filter(!is.na(variant)) %>%
  count(variant, sort = TRUE)

var_freq_pink1               ### Most common variants (individually)



pairs_pink1 <- PINK1_raw %>%
  filter(!is.na(var_1_g), !is.na(var_2_g)) %>%
  mutate(
    var_a = pmin(var_1_g, var_2_g),
    var_b = pmax(var_1_g, var_2_g)
  ) %>%
  count(var_a, var_b, sort = TRUE)

##################################################### Checking top partners for any given variant
pairs_pink1 %>%
  filter(var_a == "pink1_Ex4del")

target_pair <- c("pink1_Ex7del", "pink1_p.Val324fs")

target_literature <- PINK1_raw %>%
  rowwise() %>%
  filter(setequal(c(var_1_g, var_2_g), target_pair)) %>%
  ungroup()

unique(target_literature$PAPER_N)

###########percentage of rearangements

pairs_pink1 %>%
  mutate(
    rearr_a = str_detect(var_a, "Ex"),
    rearr_b = str_detect(var_b, "Ex")
  ) %>%
  mutate(
    category = case_when(
      rearr_a & rearr_b ~ "rearr + rearr",
      rearr_a | rearr_b ~ "rearr + SNV",
      TRUE ~ "SNV + SNV"
    )
  ) %>%
  group_by(category) %>%
  summarise(n = sum(n), .groups = "drop")

# SNV + SNV        36 --> 16/19 (84.21%)
# rearr + SNV     115 --> 1/19 (5.26%)
# rearr + rearr    90 --> 2/19 (10.52%)



write.csv(pairs_pink1, 
          "/variant_pair_ranking.csv", 
          row.names = FALSE)


length(unique(PINK1_raw$PAPER_N))
## 243 cases accross 64 papers
## 2 cases dropped after benign variants filtered out


############################################################################## Population stratification

table(PINK1_raw$Population)

PINK1_raw <- PINK1_raw %>%
  mutate(
    Population_clean = str_to_lower(Population),
    Population_continent = case_when(
      
      # EUROPE
      str_detect(Population_clean, "europe|caucasian|french|german|irish|italian|italy|polish|serbian|swiss|uk|ukrainian|czech|netherlands|polish|finnland|france|belgian|spain|norway") ~ "EUR",
      
      #Middle East
      str_detect(Population_clean, "cyprus|turkish|yemen") ~ "MDE",
      
      # EAST ASIA
      str_detect(Population_clean, "china|chinese|japan|japanese|korea|korean|taiwan|vietnam|filipino") ~ "EAS",
      
      # AFRICA
      str_detect(Population_clean, "african|tunisia") ~ "AFR",
      
      # LATIN AMERICA / ADMIXED AMERICAN
      str_detect(Population_clean, "mexico|mexican|brazil|peru") ~ "AMR",
      
      # NORTH AMERICA (ambiguous, likely EUR )
      str_detect(Population_clean, "north american") ~ "EUR",
      
      TRUE ~ "Other"
    )
  )



table(PINK1_raw$Population_continent)

pairs_by_continent <- PINK1_raw %>%
  filter(!is.na(var_1_g), !is.na(var_2_g), !is.na(Population_continent)) %>%
  mutate(
    var_a = pmin(var_1_g, var_2_g),
    var_b = pmax(var_1_g, var_2_g)
  ) %>%
  count(Population_continent, var_a, var_b, sort = TRUE)

top_pairs_by_continent <- pairs_by_continent %>%
  group_by(Population_continent) %>%
  slice_max(n, n = 5, with_ties = FALSE) %>%
  ungroup()

top_pairs_by_continent


###### check exclusivity

pair_exclusivity <- pairs_by_continent %>%
  group_by(var_a, var_b) %>%
  mutate(n_continents = n_distinct(Population_continent)) %>%
  ungroup()
exclusive_pairs <- pair_exclusivity %>%
  filter(n_continents == 1)

exclusive_pairs %>%
  arrange(Population_continent, desc(n))

exclusive_summary <- pairs_by_continent %>%
  group_by(var_a, var_b) %>%
  mutate(n_continents = n_distinct(Population_continent)) %>%
  ungroup() %>%
  mutate(is_exclusive = n_continents == 1) %>%
  group_by(Population_continent) %>%
  summarise(
    total_pairs = n(),                         # number of distinct pairs in that continent
    exclusive_pairs = sum(is_exclusive),       # how many are exclusive
    prop_exclusive = exclusive_pairs / total_pairs
  )

exclusive_summary


############################################################################################################################################
########################################################################## OTHERS ######################################################################
############################################################################################################################################
############################################################################################################################################
others_vars_raw <- SNVs_clean %>%
  filter(Gene.refGene != "PRKN" & Gene.refGene != "PINK1" & gene != "PINK1")

OTHERS_raw <- ch_filtered %>%
  filter(Gene != "PRKN" & Gene != "PINK1")

length(unique(OTHERS_raw$PAPER_N))

length(unique(c(OTHERS_raw$var_1_g,OTHERS_raw$var_2_g)))

length(OTHERS_raw$IID)
table(OTHERS_raw$Gene)

##96 unique variants (all)
library(purrr)

######## Checking rearrangements

rear_others <- SVs_clean %>%
  filter(gene != "PRKN" & gene != "PINK1")


####################################################### Checking SNVs and small indels
length(others_vars_raw$ExonicFunc.refGene)
## 66 variants SNV / small indels
table(others_vars_raw$ExonicFunc.refGene)
#"." are splice variants

###################################################### counts per variant

length(others_vars_raw$unique_variants)
## 44 unique SNVs 

## 44 Short vars + 51 exon rearrangements

var_freq_others <- OTHERS_raw %>%
  select(var_1_g, var_2_g) %>%
  pivot_longer(cols = everything(), values_to = "variant") %>%
  filter(!is.na(variant)) %>%
  count(variant, sort = TRUE)

var_freq_others               ### Most common variants (individually)



pairs_others <- OTHERS_raw %>%
  filter(!is.na(var_1_g), !is.na(var_2_g)) %>%
  mutate(
    var_a = pmin(var_1_g, var_2_g),
    var_b = pmax(var_1_g, var_2_g)
  ) %>%
  count(var_a, var_b, sort = TRUE)

##################################################### Checking top partners for any given variant
pairs_others %>%
  filter(var_a == "others_Ex4del")

target_pair <- c("others_Ex7del", "others_p.Val324fs")

target_literature <- OTHERS_raw %>%
  rowwise() %>%
  filter(setequal(c(var_1_g, var_2_g), target_pair)) %>%
  ungroup()

unique(target_literature$PAPER_N)

###########percentage of rearangements

pairs_others %>%
  mutate(
    rearr_a = str_detect(var_a, "Ex"),
    rearr_b = str_detect(var_b, "Ex")
  ) %>%
  mutate(
    category = case_when(
      rearr_a & rearr_b ~ "rearr + rearr",
      rearr_a | rearr_b ~ "rearr + SNV",
      TRUE ~ "SNV + SNV"
    )
  ) %>%
  group_by(category) %>%
  summarise(n = sum(n), .groups = "drop")



write.csv(pairs_others, 
          "variant_pair_ranking.csv", 
          row.names = FALSE)


length(unique(OTHERS_raw$PAPER_N))
## 243 cases accross 64 papers
## 2 cases dropped after benign variants filtered out


############################################################################## Population stratification

table(OTHERS_raw$Population)

OTHERS_raw <- OTHERS_raw %>%
  mutate(
    Population_clean = str_to_lower(Population),
    Population_continent = case_when(
      
      # EUROPE
      str_detect(Population_clean, "europe|caucasian|french|german|irish|italian|italy|polish|serbian|swiss|uk|ukrainian|czech|netherlands|polish|finnland|france|belgian|spain|norway") ~ "EUR",
      
      #Middle East
      str_detect(Population_clean, "cyprus|turkish|yemen") ~ "MDE",
      
      # EAST ASIA
      str_detect(Population_clean, "china|chinese|japan|japanese|korea|korean|taiwan|vietnam|filipino") ~ "EAS",
      
      # AFRICA
      str_detect(Population_clean, "african|tunisia") ~ "AFR",
      
      # LATIN AMERICA / ADMIXED AMERICAN
      str_detect(Population_clean, "mexico|mexican|brazil|peru") ~ "AMR",
      
      # NORTH AMERICA (ambiguous, likely EUR )
      str_detect(Population_clean, "north american") ~ "EUR",
      
      TRUE ~ "Other"
    )
  )



table(OTHERS_raw$Population_continent)

pairs_by_continent <- OTHERS_raw %>%
  filter(!is.na(var_1_g), !is.na(var_2_g), !is.na(Population_continent)) %>%
  mutate(
    var_a = pmin(var_1_g, var_2_g),
    var_b = pmax(var_1_g, var_2_g)
  ) %>%
  count(Population_continent, var_a, var_b, sort = TRUE)

top_pairs_by_continent <- pairs_by_continent %>%
  group_by(Population_continent) %>%
  slice_max(n, n = 5, with_ties = FALSE) %>%
  ungroup()

top_pairs_by_continent


###### check exclusivity

pair_exclusivity <- pairs_by_continent %>%
  group_by(var_a, var_b) %>%
  mutate(n_continents = n_distinct(Population_continent)) %>%
  ungroup()
exclusive_pairs <- pair_exclusivity %>%
  filter(n_continents == 1)

exclusive_pairs %>%
  arrange(Population_continent, desc(n))

exclusive_summary <- pairs_by_continent %>%
  group_by(var_a, var_b) %>%
  mutate(n_continents = n_distinct(Population_continent)) %>%
  ungroup() %>%
  mutate(is_exclusive = n_continents == 1) %>%
  group_by(Population_continent) %>%
  summarise(
    total_pairs = n(),                         # number of distinct pairs in that continent
    exclusive_pairs = sum(is_exclusive),       # how many are exclusive
    prop_exclusive = exclusive_pairs / total_pairs
  )

exclusive_summary


